<?php
require_once('/var/www/lib/functions.php');
require_once('/var/www/lib/PHPExcel.php');
require_once('/var/www/lib/PHPExcel/Writer/Excel2007.php');
require_once('/var/www/lib/PHPMailer-master/class.phpmailer.php');
require_once('/var/www/lib/PHPMailer-master/class.smtp.php');
$curr_date = date('d.m.y');
$set_date = '13.06.2021';
/**
 * Обрабатываем странички с ценами
 */
//$all_files = glob('/var/www/rozetka.ua/content_mp/'.$set_date.'/*.txt');

$files = array_values( preg_grep( '/^((?!&producer).)*$/', glob("/var/www/rozetka.ua/content/13.06.2021/*.txt") ) );
//print_r($files);die();
//	foreach ($files as $url) {
//		if (stripos($url, '/') !== false) {
//			preg_match("~/var/www/rozetka.ua/content_mp/.*/(.+).txt~isU", $url, $matches);
			
			//$id = preg_replace('/[^a-zA-Z0-9&]/', '', $url);
//			$items_urls[$matches[1]] = $url; // Заносим в массив id и адрес странички, чтобы её было легче найти при обработке
//		}
//	}
$for_translate = array();
$for_translate_val = array();

$itemBase = array();
foreach ($files as $urlpath) {
		if (file_exists($urlpath)) {
			echo $urlpath.PHP_EOL;
			$content = file_get_contents($urlpath);
			// Код товара
			preg_match("~class=\"product__code-accent.*>.*>(.+)<~isU", $content, $matches_code);

			@$code = str_replace('&nbsp;', '', $matches_code[1]);
			$code = trim($code);
			// Раздел
			preg_match_all("~class=\"breadcrumbs__link.*span>(.+)<~isU", $content, $matches_catalogue);
			//print_r($matches_catalogue);
			@$catalogue = trim($matches_catalogue[1][count($matches_catalogue[1])-2]);
			// Бренд
			preg_match_all("~class=\"breadcrumbs__link.*span>(.+)<~isU", $content, $matches_brand);
			@$brand = trim(str_replace($catalogue, '', trim(end($matches_brand[1]))));
			
			// Полное наименование товара
			preg_match("~<h1.*>(.+)<~isU", $content, $matches_name);
			@$name = trim($matches_name[1]);
			// Цена продажи
			preg_match("~http://schema.org/InStock.*price.*:(.+),~isU", $content, $matches_price);
			//print_r($matches_price);
			@$price = preg_replace('~[^\d.]+~', '' , $matches_price[1]);
			// Продавец этого товара
			preg_match("~class=\"product-seller__logo.*alt=\"(.+)\"~isU", $content, $matches_seller);
			@$seller = trim($matches_seller[1]);
			// Статус позиции (в наличии, не в наличии и т.д.)
			//preg_match("~name=\"detail_status\">(.+)<~isU", $content, $matches_status);
			preg_match("~sell_status:\"(.+)\"~isU", $content, $matches_status);
			@$status = trim($matches_status[1]);

			preg_match("~product__rating-reviews\" href=\"(.+)\"~isU", $content, $matches_url);
			@$url = trim(str_replace('comments/', '', $matches_url[1]));

			preg_match("~article&q;:&q;(.+)&q;~isU", $content, $matches_model);
			@$model = trim($matches_model[1]);

			preg_match_all("~characteristics-full__label\">(.+)<.*class=\"characteristics-full__sub-list\">(.+)</ul~isU", $content, $matches_filters, PREG_SET_ORDER);
			//print_r($matches_filters);
/*

			echo $code.PHP_EOL;
			echo $catalogue.PHP_EOL;
			echo $brand.PHP_EOL;
			echo $name.PHP_EOL;
			echo $price.PHP_EOL;
			echo $seller.PHP_EOL;
			echo $status.PHP_EOL;
			echo $url.PHP_EOL;
			echo $model.PHP_EOL;
			die();
*/


			foreach ($matches_filters as $key => $value) {
				$sp_text = '';
				//echo PHP_EOL.strip_tags($value[1]).":   ";
				preg_match_all("~<li.*>.*>.*>(.+)</li>~isU", $value[2], $ff, PREG_SET_ORDER);
				foreach ($ff as $k => $cur_f) {
					$sp_text .= strip_tags(str_replace("\n", ", ", $cur_f[1])).", ";
				}
				$sp_text = substr(trim($sp_text), 0, -1);
				$itemdBase[$catalogue][$name]['spec'][strip_tags($value[1])] = $sp_text;
				$itemdBase[$catalogue][$name]['brand'] = $brand;
				$itemdBase[$catalogue][$name]['code'] = $code;


				if (!is_numeric(strip_tags($value[1]))) {
					$for_translate[] = strip_tags($value[1]);
				}
				if (!is_numeric($sp_text)) {
					$for_translate_val[] = $sp_text;
				}
				
			}
			
				//print_r($itemdBase);
				//die();
			
		}
}



$for_translate = array_unique($for_translate);
$for_translate_val = array_unique($for_translate_val);

file_put_contents('/var/www/rozetka.ua/for_translate.txt', print_r($for_translate, 1));
file_put_contents('/var/www/rozetka.ua/for_translate_val.txt', print_r($for_translate_val, 1));
//die();
/*
echo 'Создаём сначала классический файл для UPDATE'.PHP_EOL;

// Создаём сначала классический файл для UPDATE

$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator("PricingLogix");
$objPHPExcel->getProperties()->setTitle('For Bonus Update');
$objPHPExcel->getProperties()->setSubject('For Bonus Update'.date('H:i:s'));
$objPHPExcel->getProperties()->setDescription("generated by PricingLogix");

$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setTitle('bonus_'.$curr_date);
$objPHPExcel->getActiveSheet()->SetCellValue('A' . 1, 'Артикул(уникальное значение)');
$objPHPExcel->getActiveSheet()->SetCellValue('B' . 1, 'Товарная категория');
$objPHPExcel->getActiveSheet()->SetCellValue('C' . 1, 'Заглавие');
$objPHPExcel->getActiveSheet()->SetCellValue('D' . 1, 'Наличие на складе(есть -1, нет -0)');
$objPHPExcel->getActiveSheet()->SetCellValue('E' . 1, 'Киев День, грн');
$objPHPExcel->getActiveSheet()->SetCellValue('F' . 1, 'Hotline.ua');
$objPHPExcel->getActiveSheet()->SetCellValue('G' . 1, 'Содержание');
$objPHPExcel->getActiveSheet()->SetCellValue('H' . 1, 'Харатеристики');
$objPHPExcel->getActiveSheet()->SetCellValue('I' . 1, 'Гарантия');
$objPHPExcel->getActiveSheet()->SetCellValue('J' . 1, 'На главную(1- выводить, пусто - не выводить)');
$objPHPExcel->getActiveSheet()->SetCellValue('K' . 1, 'Rozetka');
$objPHPExcel->getActiveSheet()->SetCellValue('L' . 1, 'Название картинки(латинскими)');
$objPHPExcel->getActiveSheet()->SetCellValue('M' . 1, 'Бренд');
$objPHPExcel->getActiveSheet()->SetCellValue('N' . 1, 'Инструкция');
$objPHPExcel->getActiveSheet()->SetCellValue('O' . 1, 'Title');
$objPHPExcel->getActiveSheet()->SetCellValue('P' . 1, 'Description');
$objPHPExcel->getActiveSheet()->SetCellValue('Q' . 1, 'Keywords');
$objPHPExcel->getActiveSheet()->SetCellValue('R' . 1, 'Модель');
$objPHPExcel->getActiveSheet()->SetCellValue('S' . 1, 'Логотипы');
$objPHPExcel->getActiveSheet()->SetCellValue('T' . 1, 'Главная категория (Выводится на Большие кнопки на Главной)');
$objPHPExcel->getActiveSheet()->SetCellValue('U' . 1, 'Тип (подкатегория)');
$objPHPExcel->getActiveSheet()->SetCellValue('V' . 1, 'для фильтра');
$objPHPExcel->getActiveSheet()->SetCellValue('W' . 1, 'Регион День, грн');
$objPHPExcel->getActiveSheet()->SetCellValue('X' . 1, 'Киев Ночь, грн');
$objPHPExcel->getActiveSheet()->SetCellValue('Y' . 1, 'Регион Ночь, грн');
$objPHPExcel->getActiveSheet()->SetCellValue('Z' . 1, '');
$objPHPExcel->getActiveSheet()->SetCellValue('AA' . 1, 'Проверка отклонения цен с W');

$i = 2;
foreach ($itemsArray as $cat => $nameinfo) {
	//echo $cat.PHP_EOL;
	//print_r($nameinfo);
	$spec_title = array();

	foreach ($nameinfo as $item_name => $item_values) { // Перебор товарных позиций
		$objPHPExcel->getActiveSheet()->SetCellValue('A' . $i, $item_values['code']); 	// Артикул
		$objPHPExcel->getActiveSheet()->SetCellValue('B' . $i, $cat); 									// Товарная категория
		$objPHPExcel->getActiveSheet()->SetCellValue('C' . $i, $item_name); 						// Заглавие
		$objPHPExcel->getActiveSheet()->SetCellValue('D' . $i, '1'); 										// Наличие
		$objPHPExcel->getActiveSheet()->SetCellValue('E' . $i, $item_values['price']); 	// Киев День, грн
	//$objPHPExcel->getActiveSheet()->SetCellValue('F' . $i, ''); 										// Hotline.ua
		@$objPHPExcel->getActiveSheet()->SetCellValue('G' . $i, $text); 									// Содержание
		@$objPHPExcel->getActiveSheet()->SetCellValue('H' . $i, $text);									// Харатеристики
	//$objPHPExcel->getActiveSheet()->SetCellValue('I' . $i, '');											// Гарантия
	//$objPHPExcel->getActiveSheet()->SetCellValue('J' . $i, '');											// На главную(1- выводить, пусто - не выводить)
	//$objPHPExcel->getActiveSheet()->SetCellValue('K' . $i, '');											// Rozetka
	//$objPHPExcel->getActiveSheet()->SetCellValue('L' . $i, '');											// Название картинки(латинскими)
		$objPHPExcel->getActiveSheet()->SetCellValue('M' . $i, $item_values['brand']);	// Бренд
	//$objPHPExcel->getActiveSheet()->SetCellValue('N' . $i, '');											// Инструкция
		$objPHPExcel->getActiveSheet()->SetCellValue('O' . $i, $item_name);							// Title
		$objPHPExcel->getActiveSheet()->SetCellValue('P' . $i, $item_name.'; '.$text);	// Description
	//$objPHPExcel->getActiveSheet()->SetCellValue('Q' . $i, '');											// Keywords
		$objPHPExcel->getActiveSheet()->SetCellValue('R' . $i, $item_name);							// Модель
	//$objPHPExcel->getActiveSheet()->SetCellValue('S' . $i, '');											// Логотипы
		$objPHPExcel->getActiveSheet()->SetCellValue('T' . $i, $cat);										// Главная категория (Выводится на Большие кнопки на Главной)
	//$objPHPExcel->getActiveSheet()->SetCellValue('U' . $i, '');											// Тип (подкатегория)
	//$objPHPExcel->getActiveSheet()->SetCellValue('V' . $i, '');											// для фильтра
	//$objPHPExcel->getActiveSheet()->SetCellValue('W' . $i, '');											// Регион День, грн
	//$objPHPExcel->getActiveSheet()->SetCellValue('X' . $i, '');											// Киев Ночь, грн
	//$objPHPExcel->getActiveSheet()->SetCellValue('Y' . $i, '');											// Регион Ночь, грн
	//$objPHPExcel->getActiveSheet()->SetCellValue('Z' . $i, '');											// 
	//$objPHPExcel->getActiveSheet()->SetCellValue('AA' . $i, '');										// Проверка отклонения цен с W
		$i++;
	}
}	

$objWriter = new PHPExcel_Writer_Excel5($objPHPExcel);
$objWriter->save('/var/www/rozetka.ua/filters_mp/'.$curr_date.'_update.xls');
*/






/**
 * Делаем файлики фильтров
 */
echo 'Делаем файлики фильтров...'.PHP_EOL;





foreach ($itemdBase as $cat => $nameinfo) {
	$curr_filter_row = 7;

	unset($objPHPExcel);
	$objPHPExcel = new PHPExcel();
	$objPHPExcel->getProperties()->setCreator("PricingLogix");
	$objPHPExcel->getProperties()->setTitle('For Bonus Filters');
	$objPHPExcel->getProperties()->setSubject('For Bonus Filters'.date('H:i:s'));
	$objPHPExcel->getProperties()->setDescription("generated by PricingLogix");

	$objPHPExcel->setActiveSheetIndex(0);
	$objPHPExcel->getActiveSheet()->setTitle('filters_'.$curr_date);


	$filters_pos_array = array(); // очищаем массив с заголовками

	echo '***'.PHP_EOL.$cat.PHP_EOL;

	$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'Алиас');
	$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'Модель');
	$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'Код');
	$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'Категория');
	$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'РИЦ');
	$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'производитель');


	$objPHPExcel->getActiveSheet()->SetCellValue('G2', '+');
	$objPHPExcel->getActiveSheet()->SetCellValue('H2', '+');
	$objPHPExcel->getActiveSheet()->SetCellValue('I2', '+');
	$objPHPExcel->getActiveSheet()->SetCellValue('J2', '+');


	//print_r($nameinfo);
	$spec_title = array();
	$curr_line = 3; // Текущая строка 1.2.3 и тд
	foreach ($nameinfo as $item_name => $item_values) { // Перебор товарных позиций
		/**
		 * Соберём все характеристики и одну переменную для описания товара
		 */
		echo $item_name.PHP_EOL;

		//if ($cat == 'Автомобильные пылесосы') {
		//	echo $item_name.PHP_EOL;
		//	print_r($item_values);
		//	die();
		//}

		$objPHPExcel->getActiveSheet()->SetCellValue('A'.$curr_line, make_alias($item_name)); // alias
		$objPHPExcel->getActiveSheet()->SetCellValue('B'.$curr_line, $item_name); // Model
		@$objPHPExcel->getActiveSheet()->SetCellValue('C'.$curr_line, $item_values['code']); // Code
		$objPHPExcel->getActiveSheet()->SetCellValue('D'.$curr_line, ''); // EMPTY
		$objPHPExcel->getActiveSheet()->SetCellValue('E'.$curr_line, $cat); // Category
		@$objPHPExcel->getActiveSheet()->SetCellValue('F'.$curr_line, $item_values['price']); // RPrice
		$objPHPExcel->getActiveSheet()->SetCellValue('G'.$curr_line, $item_values['brand']); // Brand

		if ($item_values['spec']) {
			foreach ($item_values['spec'] as $f_key => $f_value) {
				//echo $f_key.': '.$f_value.PHP_EOL;
				if (array_search($f_key, $filters_pos_array) !== false) {
					$curr_filter_row = array_search($f_key, $filters_pos_array);
				} else {
					$filters_pos_array[] = $f_key;
					$curr_filter_row = array_search($f_key, $filters_pos_array);
				}
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow( $curr_filter_row+7, 1, $f_key); // Заголовок
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow( $curr_filter_row+7, $curr_line, $f_value); // Значение
			}
		}
		//print_r($filters_pos_array);
		$curr_line++;

	}
	$cat = str_replace('/', '-', $cat);
	$objWriter = new PHPExcel_Writer_Excel5($objPHPExcel);
	$objWriter->save('/var/www/rozetka.ua/filters_mp2/'.$curr_date.'_'.$cat.'_filters_update.xls');
	unset($objWriter);
	//if ($cat == 'Автомобильные пылесосы') {
	//	die();
	//}
}	


function rus2translit($string) {
    $converter = array(
        'а' => 'a',   'б' => 'b',   'в' => 'v',
        'г' => 'g',   'д' => 'd',   'е' => 'e',
        'ё' => 'e',   'ж' => 'zh',  'з' => 'z',
        'и' => 'i',   'й' => 'y',   'к' => 'k',
        'л' => 'l',   'м' => 'm',   'н' => 'n',
        'о' => 'o',   'п' => 'p',   'р' => 'r',
        'с' => 's',   'т' => 't',   'у' => 'u',
        'ф' => 'f',   'х' => 'h',   'ц' => 'c',
        'ч' => 'ch',  'ш' => 'sh',  'щ' => 'sch',
        'ь' => '\'',  'ы' => 'y',   'ъ' => '\'',
        'э' => 'e',   'ю' => 'yu',  'я' => 'ya',
        
        'А' => 'A',   'Б' => 'B',   'В' => 'V',
        'Г' => 'G',   'Д' => 'D',   'Е' => 'E',
        'Ё' => 'E',   'Ж' => 'Zh',  'З' => 'Z',
        'И' => 'I',   'Й' => 'Y',   'К' => 'K',
        'Л' => 'L',   'М' => 'M',   'Н' => 'N',
        'О' => 'O',   'П' => 'P',   'Р' => 'R',
        'С' => 'S',   'Т' => 'T',   'У' => 'U',
        'Ф' => 'F',   'Х' => 'H',   'Ц' => 'C',
        'Ч' => 'Ch',  'Ш' => 'Sh',  'Щ' => 'Sch',
        'Ь' => '\'',  'Ы' => 'Y',   'Ъ' => '\'',
        'Э' => 'E',   'Ю' => 'Yu',  'Я' => 'Ya',
    );
    return strtr($string, $converter);
}
function make_alias($str) {
    // переводим в транслит
    $str = rus2translit($str);
    // в нижний регистр
    $str = strtolower($str);
    // заменям все ненужное нам на "-"
    $str = preg_replace('~[^-a-z0-9_]+~u', '_', $str);
    // удаляем начальные и конечные '-'
    $str = trim($str, "_");
    return $str;
}

function make_code($str, $brand) {
    // переводим в транслит
    $str = rus2translit($str);
    // в нижний регистр
    $str = strtolower($str);
    // заменям все ненужное нам на ""
    if ($brand) {
    	$str = str_replace(strtolower($brand), '', $str);
    }
    
    $str = preg_replace('~[^-a-z0-9_]+~u', '', $str);
    // удаляем начальные и конечные '-'
    $str = trim($str, "-");
    return $str;
}
